{
 "title": "Demo Expenses Dashboard",
 "time": { "from": "2020-11-24T11:44:18.375Z", "to": "2020-11-24T11:44:34.171Z" },
 "panels": [
  {
   "title": "Expense List Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_org_acme_rest_json_ExpenseResource_callsToExpenseList_total"
    }
   ]
  },
  {
   "title": "Calls to Expense Create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_org_acme_rest_json_ExpenseResource_callsToExpenseCreate_total"
    }
   ]
  },
  {
   "title": "Biggest expense",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_org_acme_rest_json_ExpenseResource_mostExpensiveBuy"
    }
   ]
  },
  {
   "title": "Expense List reqs/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_org_acme_rest_json_ExpenseResource_expenseListTimer_one_min_rate_per_second\n"
    }
   ]
  }
 ]
}